### PR TITLE
Updated Readme

### PR DESCRIPTION
**Pull request by hazratali**
Added conference link

### CODE REVIEW

**Comment by hazratali** [comment]
Added conference link

**Review by rizwanqureshi12 — APPROVED** [review]

**Review by rizwanqureshi12 — APPROVED** [review]

**Comment by hazratali** [comment]
Added paper link and bibtex entry.

**Comment by rizwanqureshi12** [comment]
Dear Dr. Hazrat Ali,

Thank you for the pull request. But, the link is not correct. It is for the
ACCV macau paper.


Kind regards,
Rizwan

**Comment by hazratali** [comment]
Yes. I realized that later.
 I will remove the link.
And create another pull request.

Regards


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Review by rizwanqureshi12 — APPROVED** [review]

**Review by rizwanqureshi12 — APPROVED** [review]

**Review by rizwanqureshi12 — APPROVED** [review]

**Pull request merged**
